"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";

import {
  clearAttendanceAction,
  markAttendanceQuickAction,
} from "@/actions/attendance.actions";
import {
  ATTENDANCE_STATUS_COLORS,
  ATTENDANCE_STATUS_DOT,
  ATTENDANCE_STATUS_LABELS,
  EDITABLE_STATUSES,
  WEEKDAY_LABELS,
} from "@/components/attendance/attendance-constants";
import { shortLeaveLabel } from "@/components/attendance/attendance-status-badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { formatDateLabel } from "@/lib/utils/dates";
import type { GridDay } from "@/services/attendance/attendance.engine";
import type { AttendanceStatus, ShortLeaveType } from "@/types/domain";

export function AttendanceCalendarGrid({
  weeks,
  editable,
  employeeId,
  monthLabel,
}: {
  weeks: GridDay[][];
  editable: boolean;
  employeeId?: string;
  monthLabel: string;
}) {
  const [selected, setSelected] = useState<GridDay | null>(null);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-3 text-xs">
        {(
          Object.entries(ATTENDANCE_STATUS_LABELS) as [AttendanceStatus, string][]
        ).map(([status, label]) => (
          <span key={status} className="inline-flex items-center gap-1.5">
            <span
              className={cn("h-3 w-3 rounded-sm", ATTENDANCE_STATUS_DOT[status])}
            />
            {label}
          </span>
        ))}
        <span className="inline-flex items-center gap-1.5">
          <span className="h-3 w-3 rounded-sm border bg-muted" />
          Unmarked
        </span>
      </div>

      <div className="overflow-x-auto rounded-lg border">
        <div className="min-w-[560px]">
          <div className="grid grid-cols-7 border-b bg-muted/40 text-center text-xs font-medium text-muted-foreground">
            {WEEKDAY_LABELS.map((d) => (
              <div key={d} className="px-1 py-2">
                {d}
              </div>
            ))}
          </div>
          {weeks.map((week, wi) => (
            <div key={wi} className="grid grid-cols-7 border-b last:border-b-0">
              {week.map((day) => (
                <GridCell
                  key={day.date}
                  day={day}
                  editable={editable}
                  onSelect={() => {
                    if (editable && day.inMonth && employeeId) {
                      setSelected(day);
                    }
                  }}
                />
              ))}
            </div>
          ))}
        </div>
      </div>

      {selected && editable && employeeId ? (
        <DayEditorDialog
          day={selected}
          employeeId={employeeId}
          monthLabel={monthLabel}
          onClose={() => setSelected(null)}
        />
      ) : null}
    </div>
  );
}

function GridCell({
  day,
  editable,
  onSelect,
}: {
  day: GridDay;
  editable: boolean;
  onSelect: () => void;
}) {
  const clickable = editable && day.inMonth;
  const status = day.status;

  let cellClass =
    "flex min-h-[52px] flex-col items-center justify-center border-r p-1 text-center last:border-r-0 sm:min-h-[64px]";

  if (!day.inMonth) {
    cellClass += " bg-muted/20 opacity-40";
  } else if (status) {
    cellClass += ` ${ATTENDANCE_STATUS_COLORS[status]} border-transparent`;
  } else if (day.isSunday) {
    cellClass += " bg-muted/60 text-muted-foreground";
  } else {
    cellClass += " bg-background text-muted-foreground hover:bg-muted/30";
  }

  if (clickable) {
    cellClass += " cursor-pointer transition-colors";
  }

  const label = status
    ? ATTENDANCE_STATUS_LABELS[status].split(" ")[0]
    : day.isSunday
      ? "Sun"
      : "";

  return (
    <button
      type="button"
      disabled={!clickable}
      onClick={onSelect}
      className={cellClass}
      title={
        day.inMonth
          ? `${formatDateLabel(day.date)}${status ? ` — ${ATTENDANCE_STATUS_LABELS[status]}` : ""}`
          : undefined
      }
    >
      <span className="text-sm font-semibold">{day.inMonth ? day.dayNum : ""}</span>
      {day.inMonth && label ? (
        <span className="mt-0.5 hidden text-[10px] font-medium leading-tight sm:block">
          {label}
        </span>
      ) : null}
      {day.isAutoGenerated ? (
        <span className="text-[9px] opacity-80">auto</span>
      ) : null}
    </button>
  );
}

function DayEditorDialog({
  day,
  employeeId,
  monthLabel,
  onClose,
}: {
  day: GridDay;
  employeeId: string;
  monthLabel: string;
  onClose: () => void;
}) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [status, setStatus] = useState<AttendanceStatus>(day.status ?? "present");
  const [shortType, setShortType] = useState<ShortLeaveType | "">(
    day.shortLeaveType ?? "",
  );
  const [error, setError] = useState<string | null>(null);

  function save() {
    startTransition(async () => {
      setError(null);
      const result = await markAttendanceQuickAction(
        employeeId,
        day.date,
        status,
        status === "short_leave" ? shortType || null : null,
      );
      if (result.error) {
        setError(result.error);
        return;
      }
      onClose();
      router.refresh();
    });
  }

  function clear() {
    startTransition(async () => {
      setError(null);
      const result = await clearAttendanceAction(employeeId, day.date);
      if (result.error) {
        setError(result.error);
        return;
      }
      onClose();
      router.refresh();
    });
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="w-full max-w-md rounded-lg border bg-card p-5 shadow-lg">
        <h3 className="text-lg font-semibold">{formatDateLabel(day.date)}</h3>
        <p className="text-sm text-muted-foreground">{monthLabel}</p>

        <div className="mt-4 space-y-3">
          <label className="text-sm font-medium">Status</label>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-3">
            {EDITABLE_STATUSES.map((s) => (
              <button
                key={s}
                type="button"
                onClick={() => setStatus(s)}
                className={cn(
                  "rounded-md border px-2 py-2 text-xs font-medium transition-colors",
                  status === s
                    ? ATTENDANCE_STATUS_COLORS[s]
                    : "bg-background hover:bg-muted",
                )}
              >
                {ATTENDANCE_STATUS_LABELS[s]}
              </button>
            ))}
          </div>

          {status === "short_leave" ? (
            <div className="space-y-1.5">
              <label className="text-sm font-medium">Short leave type</label>
              <select
                value={shortType}
                onChange={(e) =>
                  setShortType(e.target.value as ShortLeaveType | "")
                }
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              >
                <option value="">Select…</option>
                <option value="late_arrival">Arrive 11:30 AM</option>
                <option value="early_departure">Leave 4:30 PM</option>
              </select>
            </div>
          ) : null}

          {day.status === "sunday_leave" && day.isAutoGenerated ? (
            <p className="text-xs text-muted-foreground">
              Auto Sunday leave (more than 2 leaves Mon–Sat in week).
            </p>
          ) : null}
          {day.shortLeaveType ? (
            <p className="text-xs text-muted-foreground">
              Current: {shortLeaveLabel(day.shortLeaveType)}
            </p>
          ) : null}

          {error ? <p className="text-sm text-destructive">{error}</p> : null}
        </div>

        <div className="mt-5 flex flex-wrap gap-2">
          <Button onClick={save} disabled={isPending}>
            {isPending ? "Saving…" : "Save"}
          </Button>
          {day.status ? (
            <Button variant="outline" onClick={clear} disabled={isPending}>
              Clear
            </Button>
          ) : null}
          <Button variant="ghost" onClick={onClose} disabled={isPending}>
            Cancel
          </Button>
        </div>
      </div>
    </div>
  );
}
