import type { AttendanceStatus, ShortLeaveType } from "@/types/domain";

export const ATTENDANCE_STATUS_LABELS: Record<AttendanceStatus, string> = {
  present: "Present",
  late: "Late",
  paid_leave: "Paid leave",
  half_day: "Half day",
  short_leave: "Short leave",
  absent: "Absent",
  sunday_leave: "Sunday leave",
};

export const ATTENDANCE_STATUS_COLORS: Record<AttendanceStatus, string> = {
  present:
    "bg-emerald-500 text-white border-emerald-600 hover:bg-emerald-600 dark:bg-emerald-600",
  late: "bg-amber-500 text-white border-amber-600 hover:bg-amber-600",
  paid_leave: "bg-blue-500 text-white border-blue-600 hover:bg-blue-600",
  half_day: "bg-violet-500 text-white border-violet-600 hover:bg-violet-600",
  short_leave: "bg-cyan-600 text-white border-cyan-700 hover:bg-cyan-700",
  absent: "bg-red-500 text-white border-red-600 hover:bg-red-600",
  sunday_leave: "bg-orange-500 text-white border-orange-600 hover:bg-orange-600",
};

export const ATTENDANCE_STATUS_DOT: Record<AttendanceStatus, string> = {
  present: "bg-emerald-500",
  late: "bg-amber-500",
  paid_leave: "bg-blue-500",
  half_day: "bg-violet-500",
  short_leave: "bg-cyan-600",
  absent: "bg-red-500",
  sunday_leave: "bg-orange-500",
};

export type GridDay = {
  date: string;
  dayNum: number;
  inMonth: boolean;
  isSunday: boolean;
  status: AttendanceStatus | null;
  shortLeaveType: ShortLeaveType | null;
  isAutoGenerated: boolean;
};

export type AttendanceGridRecord = {
  attendance_date: string;
  status: AttendanceStatus;
  short_leave_type?: ShortLeaveType | null;
  is_auto_generated?: boolean;
};

export const WEEKDAY_LABELS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const EDITABLE_STATUSES: AttendanceStatus[] = [
  "present",
  "late",
  "paid_leave",
  "half_day",
  "short_leave",
  "absent",
];
