import assert from "node:assert/strict";
import test from "node:test";

import { attendanceDayCode } from "@/lib/reports/attendance-code";
import type { GridDay } from "@/services/attendance/attendance.engine";

function day(
  overrides: Partial<GridDay> & Pick<GridDay, "date" | "dayNum">,
): GridDay {
  return {
    inMonth: true,
    isSunday: false,
    status: null,
    shortLeaveType: null,
    isAutoGenerated: false,
    ...overrides,
  };
}

test("attendanceDayCode: paid leave is PL and short leave is SL", () => {
  assert.equal(
    attendanceDayCode(
      day({ date: "2026-06-03", dayNum: 3, status: "paid_leave" }),
      null,
    ),
    "PL",
  );
  assert.equal(
    attendanceDayCode(
      day({ date: "2026-06-03", dayNum: 3, status: "short_leave" }),
      null,
    ),
    "SL",
  );
});
